format = "$directory$git_branch$character"
add_newline = true

[git_branch]
format ='[ðŸŒµ<$branch>(:$remote_branch)]($style) '
style = 'bold red'
truncation_symbol = ''

[directory]
truncation_length = 1

[git_commit]
format ='[\($hash$tag\)]'
tag_disabled = false

[character] # The name of the module we are configuring is 'character'
success_symbol = '[âžœ](bold blue)'
error_symbol = '[X](bold red)'

